# Generated by Django 3.2.6 on 2022-09-13 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lecturer_offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('bio', models.TextField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('activated', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lecturer_offices.lectureroffice')),
            ],
        ),
    ]
