# Generated by Django 3.2.6 on 2022-09-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_offices', '0001_initial'),
        ('profiles', '0002_auto_20220913_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lecturer_offices.lectureroffice'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
