# Generated by Django 3.2.6 on 2022-09-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220913_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created',
            new_name='timestamp',
        ),
    ]
