# Generated by Django 3.2.6 on 2022-09-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='days_of_the_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255, null=True),
        ),
    ]
