# Generated by Django 3.2.6 on 2022-09-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseunit',
            old_name='created',
            new_name='timestamp',
        ),
    ]
