# Generated by Django 3.2.6 on 2022-09-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit_name', models.CharField(max_length=255, null=True)),
                ('course_unit_code', models.CharField(max_length=255, null=True)),
                ('room_number', models.CharField(max_length=255, null=True)),
                ('block', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=255, null=True)),
                ('exam_date', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
